# Generated by Django 3.2.6 on 2021-10-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_orderplaced_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T', 'Trending Deals'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('FW', 'Foot Wear'), ('BP', 'Beauty Products'), ('F', 'Furnitures'), ('M', 'Mobiles'), ('L', 'Laptops'), ('C', 'Consoles'), ('EA', 'Electronics Accessories'), ('G', 'Games'), ('TV', 'Televisions'), ('HA', 'Home Appliances')], max_length=2),
        ),
    ]
